version: '3.8'

services:
  dagster:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./crypto_pipeline:/app/crypto_pipeline
      - ./.dagster:/app/.dagster
    environment:
      - DAGSTER_HOME=/app/.dagster
    command: python -m dagster dev -m crypto_pipeline -p 3000 -h 0.0.0.0 